version: '3'
services:
  website:
    container_name: php72
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - "30001:80"
#    depends_on:
#      - mysql

    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql8
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
      - MYSQL_DB=my_note

  mysql:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=my_note
      - MYSQL_USER=root
      - MYSQL_PASSWORD='' 
#      - MYSQL_HOST=localhost
#    ports:
#      - "30002:3306"
#    volumes:
#      -.:/var/www/html
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30003:80"
    environment:
      - PMA_HOST=mysql8
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: phpmyadmin_container
networks:
  frontend:
  backend:
